### ISSUE TITLE
Question: about 'tsi_buff' address in core/arch/arm/plat-nuvoton/pta/crypto_pta.c

### ISSUE THREAD

**Issue by KunYi** [OpenNuvoton/MA35D1_optee_os-v3.9.0#1]
please check Line 246 and Line 416 in core/arch/arm/plat-nuvoton/pta/crypto_pta.c
TSI operation need physical address

https://github.com/OpenNuvoton/MA35D1_optee_os-v3.9.0/blob/1d2d0fbf50c7ead2bcef2a11f6c676979d17de47/core/arch/arm/plat-nuvoton/pta/crypto_pta.c#L246

https://github.com/OpenNuvoton/MA35D1_optee_os-v3.9.0/blob/1d2d0fbf50c7ead2bcef2a11f6c676979d17de47/core/arch/arm/plat-nuvoton/pta/crypto_pta.c#L412-L418

maybe need modify to **(uint32_t)virt_to_phys(tsi_buff)**

**Comment by ychuang3** [comment]
Issue fixed in the latest commit.
Thanks for your comments.

**Comment by KunYi** [comment]
Good job!
