### ISSUE TITLE
suggestion modify to __aligned(64) static unsigned char tsi_patch_image[]

### ISSUE THREAD

**Issue by KunYi** [OpenNuvoton/MA35D1_optee_os-v3.9.0#2]
please add **__aligned(64) static** for **tsi_patch_image** variable
testing with gcc 11.2/11.3 need the attribute for  va 2 pa mapping

https://github.com/OpenNuvoton/MA35D1_optee_os-v3.9.0/blob/1d2d0fbf50c7ead2bcef2a11f6c676979d17de47/core/arch/arm/plat-nuvoton/tsi_patch.c#L1-L5

**Comment by ychuang3** [comment]
Issue fixed in the latest commit.

**Comment by KunYi** [comment]
Thanks you!
